const explanations: Record<string, [string, string, string]> = {
  "match-participant.scheduling": ["Entra en el chat para proponer cuándo y dónde jugar y acordarlo con los demás participantes.", "Open the chat to propose when and where to play and agree with the other players.", "Sartu txatean noiz eta non jokatu proposatzeko eta beste jokalariekin adosteko."],
  "match-participant.coordinating": ["Entra en el chat para revisar y responder las propuestas y acordar fecha, hora y lugar de juego.", "Open the chat to review and answer proposals and agree on a date, time and venue.", "Sartu txatean proposamenak berrikusi eta erantzuteko, eta eguna, ordua eta lekua adosteko."],
  "match-participant.awaiting_booking": ["Ya hay acuerdo para jugar. Revisa y confirma la reserva de pista desde el chat o el detalle del partido.", "Players have agreed to play. Review and confirm the court booking in the chat or match details.", "Jokatzeko adostasuna dago. Berrikusi eta baieztatu pistaren erreserba txatean edo partidaren xehetasunetan."],
  "match-participant.scheduled": ["Tu partido tiene fecha y hora. Abre el detalle para consultar la pista y añadirlo a tu calendario.", "Your match has a date and time. Open its details to check the court and add it to your calendar.", "Zure partidak eguna eta ordua ditu. Ireki xehetasunak pista ikusteko eta egutegian gehitzeko."],
  "match-participant.in_progress": ["Tu partido está en curso. Cuando terminéis, entra en el partido para consultar las acciones del resultado.", "Your match is in progress. When you finish, open the match to check the available result actions.", "Zure partida jokoan dago. Amaitzean, sartu partidan emaitzaren aukerak ikusteko."],
  "match-participant.result_pending": ["Falta el resultado de tu partido. Abre el detalle para consultar las acciones disponibles para registrarlo.", "Your match result is missing. Open the details to check the available actions for recording it.", "Zure partidaren emaitza falta da. Ireki xehetasunak erregistratzeko aukerak ikusteko."],
  "match-participant.record_result": ["Falta el resultado de tu partido. Regístralo en el apartado de resultado de la pantalla del partido.", "Your match result is missing. Record it in the result section of the match screen.", "Zure partidaren emaitza falta da. Erregistratu partidaren pantailako emaitzaren atalean."],
  "match-participant.postponed": ["Tu partido se ha aplazado. Entra en el chat para acordar una nueva fecha con los demás jugadores.", "Your match was postponed. Open the chat to agree on a new date with the other players.", "Zure partida atzeratu da. Sartu txatean beste jokalariekin data berria adosteko."],
  "confirmation.action_pending": ["Revisa el resultado registrado y confirma si es correcto o indica que no estás de acuerdo.", "Review the recorded result and confirm it or indicate that you disagree.", "Berrikusi erregistratutako emaitza eta baieztatu zuzena den edo adierazi desadostasuna."],
  "chat.readonly": ["Este chat es de solo lectura; no se pueden enviar nuevos mensajes.", "This chat is read-only; new messages cannot be sent.", "Txat hau irakurtzeko soilik da; ezin da mezurik bidali."],
  "statistics.incomplete": ["Faltan resultados o detalles de partidos para completar las estadísticas de la temporada.", "Match results or details are missing from the season statistics.", "Partiden emaitzak edo xehetasunak falta dira denboraldiko estatistikak osatzeko."],
  "match.scheduling": ["Todavía no se han acordado la fecha y la hora del partido.", "The match date and time have not been agreed yet.", "Partidaren eguna eta ordua oraindik ez dira adostu."],
  "match.coordinating": ["Los jugadores están acordando cuándo o dónde jugar.", "Players are agreeing when or where to play.", "Jokalariak noiz edo non jokatu adosten ari dira."],
  "match.awaiting_booking": ["Ya hay acuerdo para jugar; falta confirmar la reserva de pista.", "Players have agreed to play; the court booking still needs confirmation.", "Jokatzeko adostasuna dago; pistaren erreserba baieztatzea falta da."],
  "match.scheduled": ["El partido tiene fecha y hora programadas.", "The match has a scheduled date and time.", "Partidak eguna eta ordua programatuta ditu."],
  "match.in_progress": ["Ha llegado la hora programada y el partido está en curso.", "The scheduled time has arrived and the match is in progress.", "Programatutako ordua iritsi da eta partida jokoan dago."],
  "match.result_pending": ["Falta registrar el resultado del partido.", "The match result still needs to be recorded.", "Partidaren emaitza erregistratzea falta da."],
  "match.finished": ["El resultado del partido ya está registrado.", "The match result has been recorded.", "Partidaren emaitza erregistratuta dago."],
  "match.postponed": ["El partido se ha aplazado y debe reprogramarse.", "The match has been postponed and needs rescheduling.", "Partida atzeratu da eta berriro programatu behar da."],
  "match.victory": ["Tu equipo ha ganado este partido.", "Your team won this match.", "Zure taldeak partida irabazi du."],
  "match.defeat": ["Tu equipo ha perdido este partido.", "Your team lost this match.", "Zure taldeak partida galdu du."],
  "round.upcoming": ["Esta jornada todavía no ha comenzado.", "This round has not started yet.", "Jardunaldi hau oraindik ez da hasi."],
  "round.active": ["Esta es la jornada que se está disputando actualmente.", "This is the round currently being played.", "Une honetan jokatzen ari den jardunaldia da."],
  "round.overdue": ["El plazo de la jornada ha terminado y quedan partidos pendientes.", "The round deadline has passed with matches still pending.", "Jardunaldiaren epea amaitu da eta partidak geratzen dira."],
  "round.completed": ["Todos los partidos de la jornada han finalizado.", "All matches in the round have finished.", "Jardunaldiko partida guztiak amaitu dira."],
  "season.none": ["La temporada todavía no tiene jornadas generadas.", "No rounds have been generated for this season yet.", "Denboraldiak oraindik ez du jardunaldirik sortuta."],
  "season.upcoming": ["Esta temporada todavía no ha comenzado.", "This season has not started yet.", "Denboraldi hau oraindik ez da hasi."],
  "season.active": ["Esta temporada está en curso.", "This season is in progress.", "Denboraldi hau martxan dago."],
  "season.finished": ["Esta temporada ha finalizado.", "This season has finished.", "Denboraldi hau amaitu da."],
  "payment.paid": ["Este pago figura como pagado.", "This payment is marked as paid.", "Ordainketa hau ordainduta ageri da."],
  "payment.pending": ["Este pago todavía no figura como pagado.", "This payment is not yet marked as paid.", "Ordainketa hau oraindik ez da ordainduta ageri."],
  "payment.pay": ["Tienes este importe pendiente de pagar.", "You still owe this amount.", "Zenbateko hau ordaintzeko duzu."],
  "payment.receive": ["Tienes este importe pendiente de cobrar.", "You are still owed this amount.", "Zenbateko hau jasotzeko duzu."],
  "payment.incomplete": ["Faltan datos para calcular los pagos del partido.", "More details are needed to calculate match payments.", "Partidaren ordainketak kalkulatzeko datuak falta dira."],
  "payment.settled": ["No quedan transferencias pendientes en este partido.", "There are no pending transfers for this match.", "Ez dago partidaren transferentziarik egiteko."],
  "payment.personal-settled": ["Tu parte está saldada, aunque puede haber pagos pendientes entre otros jugadores.", "Your balance is settled; other players may still have pending payments.", "Zure zatia kitatuta dago; beste jokalariek ordainketak izan ditzakete."],
  "incident.pending": ["La incidencia está pendiente de resolución.", "The incident is awaiting resolution.", "Gertakaria ebazteko dago."],
  "incident.resolved": ["La incidencia ya ha sido resuelta.", "The incident has been resolved.", "Gertakaria ebatzita dago."],
  "confirmation.pending": ["El resultado espera la validación de los participantes.", "The result is awaiting participant confirmation.", "Emaitza parte-hartzaileen baieztapenaren zain dago."],
  "confirmation.validated": ["El resultado ha sido validado.", "The result has been confirmed.", "Emaitza baieztatu da."],
  "confirmation.auto_validated": ["El resultado se ha validado automáticamente al terminar el plazo.", "The result was confirmed automatically when the deadline expired.", "Emaitza automatikoki baieztatu da epea amaitzean."],
  "confirmation.disputed": ["Hay desacuerdo con el resultado y debe revisarse.", "The result has been disputed and needs review.", "Emaitzarekin desadostasuna dago eta berrikusi behar da."],
  "confirmation.locked": ["El resultado es definitivo y está bloqueado.", "The result is final and locked.", "Emaitza behin betikoa da eta blokeatuta dago."],
  "confirmation.optional": ["La confirmación del resultado es opcional.", "Result confirmation is optional.", "Emaitzaren baieztapena aukerakoa da."],
}
export function getStatusExplanation(kind: string, status: string, locale: string) {
  const normalized = kind === "round" && status === "finished" ? "completed" : status
  const explanation = explanations[`${kind}.${normalized}`] ?? (kind === "match-participant" ? explanations[`match.${normalized}`] : undefined)
  return explanation?.[locale === "en" ? 1 : locale === "eu" ? 2 : 0] ?? ""
}
