import { readFile } from "node:fs/promises"
import { describe, expect, it } from "vitest"

const read = (path: string) => readFile(path, "utf8")

describe("match detail pairing panel", () => {
  it("keeps the pending versus view but promotes a vertical result layout when scores exist", async () => {
    const [panel, leaguePage, personalPage, personalServer, personalModel, personalDetailModel, sharedView] = await Promise.all([
      read("src/components/match/MatchDetailPairingPanel.tsx"),
      read("src/app/match/[id]/page.tsx"),
      read("src/app/personal-matches/[id]/page.tsx"),
      read("src/lib/serverPersonalMatches.ts"),
      read("src/lib/personalMatches.ts"),
      read("src/lib/personalMatchDetailModel.ts"),
      read("src/components/match/MatchDetailView.tsx"),
    ])

    expect(panel).not.toContain(">\n          Emparejamiento\n        </h2>")
    expect(panel).toContain('const hasResult = sets.length > 0 || (pointsA !== null && pointsB !== null)')
    expect(panel).toContain('<FinishedPairRow')
    expect(panel).toContain('function FinishedPairRow({')
    expect(panel).not.toContain('alignment: "left" | "right"\n  showAvatars: boolean')
    expect(panel).not.toContain('showAvatars={showAvatars}')
    expect(panel).toContain('className="space-y-2.5"')
    expect(panel).toContain('rounded-2xl bg-neutral-50 px-3 py-3 sm:px-4 sm:py-3.5')
    expect(panel).toContain('grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3')
    expect(panel).not.toContain('rounded-xl bg-white px-2.5 py-2 ring-1 ring-neutral-200')
    expect(panel).not.toContain('shrink-0 rounded-xl bg-white px-2 py-2 ring-1 ring-neutral-200')
    expect(panel).toContain('import { SetGameScore } from "@/components/matches/SetGameScore"')
    expect(panel).toContain('<SetGameScore key={index} value={ownScore} won={ownScore > rivalScore} />')
    expect(panel).not.toContain('type-caption font-bold uppercase tracking-wide text-neutral-400')
    expect(panel).toContain('function FinishedPlayerName({')
    expect(panel).toContain('metadataPlacement: "before-name" | "after-name"')
    expect(panel).toContain('metadataPlacement={index === 0 ? "before-name" : "after-name"}')
    expect(panel).toContain('const positionLine = <p className={metadataClass}>{position ? tx(`#${position} en liga`) : "\\u00a0"}</p>')
    expect(panel).toContain("const playLine = playerPositionLabel ? (")
    expect(panel).toContain("{showRankingPosition ? positionLine : null}")
    expect(panel).not.toContain('positionPlacement: "above" | "below"')
    expect(panel).toContain('side="a"')
    expect(panel).toContain('side="b"')
    expect(panel).not.toContain('mb-1.5 text-left type-caption font-bold uppercase leading-none tracking-wide text-neutral-500')
    expect(panel).not.toContain('mt-1.5 text-left type-caption font-bold uppercase leading-none tracking-wide text-neutral-500')
    expect(panel).not.toContain('bg-neutral-100 font-black text-neutral-800 ring-neutral-200')
    expect(panel).not.toContain('bg-neutral-50 font-bold text-neutral-500 ring-neutral-200')
    expect(panel).toContain('h-9 min-w-9 items-center justify-center self-center rounded-md')
    expect(panel).toContain('text-base font-black leading-none text-neutral-950 ring-1 ring-inset ring-neutral-200 shadow-sm')
    expect(panel).toContain('relative -translate-y-0.5 ml-1 flex h-9 min-w-9 items-center justify-center self-center rounded-md bg-white px-2')
    expect(panel).toContain('label={tx("Pareja A")}')
    expect(panel).toContain('label={tx("Pareja B")}')
    expect(panel).toContain('const pairPlayers = playerIds.map')
    expect(panel).toContain('<PlayerAvatar')
    expect(panel).toContain('size="md"')
    expect(panel).toContain('const showAvatars = [...teamA, ...teamB].some')
    expect(panel).toContain('isSafeImageUrl(getPlayerById(playerId, players)?.avatarUrl)')
    expect(panel).toContain('alignment === "right" ? "justify-end" : "justify-start"')
    expect(panel).toContain('type-player-name-prominent')
    expect(panel).not.toContain('line-clamp-2')
    expect(panel).not.toContain('[overflow-wrap:anywhere]')
    expect(panel).toContain('truncate whitespace-nowrap type-player-name-prominent')
    expect(panel).toContain('`#${position} en liga`')
    const finishedPlayer = panel.slice(panel.indexOf("function FinishedPlayerName({"), panel.indexOf("function FinishedPairRow({"))
    expect(finishedPlayer).toContain("getPlayerSideAndHandLabel")
    expect(finishedPlayer).toContain("showPlayerMetadata && playerPositionLabel")
    expect(finishedPlayer).not.toContain("en liga")
    expect(panel).toContain('alignment="left"')
    expect(panel).toContain('alignment="right"')
    expect(panel).toContain('className="min-w-0 text-left"')
    expect(panel).toContain('alignment === "right" ? "text-right" : "text-left"')
    expect(panel).toContain('type-caption font-bold uppercase leading-none tracking-wide')
    expect(panel).toContain('mr-auto flex h-7 min-w-7')
    expect(panel).toContain('ml-auto flex h-7 min-w-7')
    expect(panel).toContain('points !== null && points !== undefined')
    expect(panel).toContain('grid grid-cols-2 items-start gap-2 sm:gap-4')
    expect(panel).toContain('relative mt-1.5 grid grid-cols-2 items-start gap-2 sm:gap-4')
    expect(panel).toContain('pointer-events-none absolute left-1/2 top-1/2 z-20')
    expect(panel).toContain('>\n                  VS\n                </span>')
    expect(panel).toContain('flex h-8 w-8 items-center justify-center rounded-full bg-neutral-950 type-caption font-black uppercase tracking-wide text-white shadow-sm')
    expect(panel).toContain('flex shrink-0 items-center gap-1.5 self-center')
    expect(panel).toContain('rounded-lg bg-neutral-50 px-2 py-1.5')
    expect(panel).toContain('border-t border-neutral-300')
    expect(panel).toContain('alignment === "right" ? "ml-4" : "mr-4"')
    expect(panel).toContain('className={index === 0 ? "pb-2" : "pt-0"}')
    expect(panel).toContain('mb-1.5 mr-1 border-t border-neutral-300')
    expect(panel).toContain('className="grid grid-cols-2 items-start gap-2 sm:gap-4"')
    expect(panel).toContain('{showAvatars ? (')
    expect(panel).toContain('<PairAvatars playerIds={teamA} players={players} alignment="left" />')
    expect(panel).toContain('<PairAvatars playerIds={teamB} players={players} alignment="right" />')
    expect(panel).toContain('className="relative mt-1.5 grid grid-cols-2 items-start gap-2 sm:gap-4"')
    expect(panel).toContain('pointer-events-none absolute left-1/2 top-1/2 z-20')

    expect(leaguePage).toContain("<MatchDetailView")
    expect(sharedView).toContain("<MatchDetailPairingPanel")
    expect(leaguePage).toContain("getRankingDisplayPosition(rankingPlayers, playerId)")
    expect(leaguePage).not.toContain("getRankingPosition(rankingPlayers, playerId)")
    expect(leaguePage).toContain("rankingPositions,")
    expect(leaguePage).not.toContain("<MatchScoreboard")

    expect(personalPage).toContain("<MatchDetailView")
    expect(personalPage).toContain("linkPlayers: false")
    expect(personalPage).toContain("showPendingPlayerMetadata: true")
    expect(personalPage).toContain("showFinishedPlayerMetadata: false")
    expect(personalPage).toContain("buildPersonalMatchDetailModel(item)")
    expect(personalDetailModel).toContain("avatarUrl: participant.avatarUrl ?? null")
    expect(personalDetailModel).toContain("preferredSide: participant.preferredSide ?? null")
    expect(personalDetailModel).toContain("dominantHand: participant.dominantHand ?? null")
    expect(sharedView).toContain("items-start justify-between")
    expect(sharedView).toContain("<MatchStatusBadge")
    expect(personalPage).not.toContain("<MatchScoreboard")

    expect(personalModel).toContain("avatarUrl?: string | null")
    expect(personalModel).toContain('preferredSide?: "drive" | "reves" | "versatile" | null')
    expect(personalModel).toContain('dominantHand?: "right" | "left" | null')
    expect(personalServer).toContain('.from("app_users")')
    expect(personalServer).toContain('.select("id,avatar_url,preferred_side,dominant_hand")')
    expect(personalServer).toContain("accountMetadataByUserId")
  })
})
