import { readFile } from "node:fs/promises"
import { describe, expect, it } from "vitest"

describe("v1.8.0 chats and polish", () => {
  it("promotes chats to player navigation with unread badge", async () => { const nav = await readFile("src/components/layout/BottomNav.tsx", "utf8"); expect(nav).toContain('href: "/chats"'); expect(nav).toContain('grid-cols-5'); expect(nav).toContain("chatUnread") })
  it("keeps finished match chats writable through the full following calendar day and read only afterwards", async () => { const api = await readFile("src/app/api/matches/[matchId]/chat/route.ts", "utf8"); const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); const shared = await readFile("src/components/match/chat/MatchChatShared.tsx", "utf8"); expect(api).toContain("match_chat_read_only"); expect(api).toContain("isMatchChatReadOnly"); expect(page).toContain("<MatchChatWriteWindowBanner"); expect(page).toContain("<MatchChatReadOnlyBar>"); expect(shared).toContain("Puedes seguir escribiendo durante todo el día"); expect(shared).toContain("El chat finalizará el") })
  it("notifies other participants and opens chat directly", async () => { const activity = await readFile("src/lib/activity.ts", "utf8"); const push = await readFile("src/lib/serverPushDispatch.ts", "utf8"); const prefs = await readFile("src/lib/notificationSettings.ts", "utf8"); const center = await readFile("src/app/notifications/page.tsx", "utf8"); expect(activity).toContain('"match_chat_message"'); expect(push).toContain('`/match/${event.match_id}/chat`'); expect(push).toContain("email === actorEmail"); expect(prefs).toContain('key: "match_chat"'); expect(prefs).not.toContain('match_chat: ["next_match"]'); expect(center).toContain('event.type === "match_chat_message" ? `/match/${event.matchId}/chat`'); expect(center).toContain("messagePreview") })
  it("keeps add location outside scroll and hides recommendations during creation", async () => { const source = await readFile("src/components/match/MatchScheduleForm.tsx", "utf8"); expect(source).toContain('shrink-0 border-t border-neutral-100 bg-white p-2'); expect(source).toContain('isAddingLeagueLocation ? <div'); expect(source.indexOf('shrink-0 border-t border-neutral-100')).toBeGreaterThan(source.indexOf('overflow-y-auto overscroll-contain')) })
  it("stores the informational preferred side", async () => { const migration = await readFile("supabase/migrations/20260812130000_add_chat_hub_and_preferred_side.sql", "utf8"); const profile = await readFile("src/components/settings/AccountProfileSettings.tsx", "utf8"); expect(migration).toContain("preferred_side"); for (const value of ["drive", "reves", "versatile"]) expect(profile).toContain(`value="${value}"`) })
  it("adds a match-detail tutorial for chat access", async () => { const tours = await readFile("src/features/onboarding/tours.ts", "utf8"); const actions = await readFile("src/components/match/MatchActionsMenu.tsx", "utf8"); const chatAction = await readFile("src/components/match/MatchChatFloatingAction.tsx", "utf8"); expect(tours).toContain('route: "/match/:id"'); expect(tours).toContain("/^\\/match\\/[^/]+$/"); expect(actions).toContain("<MatchChatActionLink"); expect(chatAction).toContain('data-tour="match-chat-access"') })
  it("uses the Ranking header and only current-season participant matches", async () => { const page = await readFile("src/app/chats/page.tsx", "utf8"); const api = await readFile("src/app/api/chats/route.ts", "utf8"); expect(page).toContain('<BackButton fallbackHref="/" label={t.common.back} />'); expect(page).toContain("<SeasonContextLine"); expect(page).toContain("seasonName={activeSeason.name}"); expect(page).toContain("seasonId: activeSeason.id"); expect(api).toContain('.eq("season_id", seasonId)'); expect(api).toContain("teamA.includes(playerId) || teamB.includes(playerId)") })
  it("describes each conversation from the viewer perspective using first names", async () => { const page = await readFile("src/app/chats/page.tsx", "utf8"); const api = await readFile("src/app/api/chats/route.ts", "utf8"); expect(page).toContain("function firstName(value: string)"); expect(page).toContain('return `${tx("con")} ${firstName(chat.partner) || tx("Pareja")} vs ${rivalLabel}`'); expect(api).toContain("ownTeam = teamA.includes(playerId) ? teamA : teamB"); expect(api).toContain("rivalTeam = teamA.includes(playerId) ? teamB : teamA"); expect(api).toContain('partner: partnerId ? name(partnerId) : "Pareja"') })
  it("uses a shared icon-only accessible send action and a clearer chat-list hierarchy", async () => { const chat = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); const shared = await readFile("src/components/match/chat/MatchChatShared.tsx", "utf8"); const sendIcon = await readFile("src/components/match/MatchChatSendIcon.tsx", "utf8"); const page = await readFile("src/app/chats/page.tsx", "utf8"); expect(chat).toContain("<MatchChatComposer"); expect(shared).toContain('aria-label={tx("Enviar mensaje")}'); expect(shared).toContain("<MatchChatSendIcon />"); expect(sendIcon).toContain('viewBox="0 0 1254 1254"'); expect(sendIcon).toContain('d="M792 127.1c-16.8 1.8-32.1 4.2-42'); expect(shared).not.toContain('{sending ? "…" : "Enviar"}'); expect(page).toContain("type-small font-semibold text-neutral-600"); expect(page).toContain("chat-list-stack"); expect(page).toContain("border-t border-neutral-100 pt-2"); })
  it("orders active conversations like messaging and scopes the navbar badge to the active season", async () => { const api = await readFile("src/app/api/chats/route.ts", "utf8"); const nav = await readFile("src/components/layout/BottomNav.tsx", "utf8"); expect(api).not.toContain("(b.unread - a.unread)"); expect(api).toContain("if (at || bt)"); expect(api).toContain("at ? -1 : 1"); expect(api).toContain("return a.round - b.round"); expect(nav).toContain('seasonId=${encodeURIComponent(activeSeason.id)}'); expect(nav).toContain("[activeLeagueId, activeSeason.id, pathname, spectatorMode]") })
  it("keeps mobile gesture areas visually continuous", async () => { const css = await readFile("src/app/globals.css", "utf8"); const nav = await readFile("src/components/layout/BottomNav.tsx", "utf8"); const shared = await readFile("src/components/match/chat/MatchChatShared.tsx", "utf8"); expect(nav).toContain('root.dataset.bottomNavVisible = "true"'); expect(css).toContain("--app-bottom-nav-safe-surface"); expect(css).toContain('data-bottom-nav-visible="true"'); expect(shared).toContain('html.dataset.matchChatActive = "true"'); expect(css).toContain("--app-match-chat-safe-surface"); expect(css).toContain('data-match-chat-active="true"'); })

  it("supports structured chat proposals with participant responses", async () => { const api = await readFile("src/app/api/matches/[matchId]/chat/route.ts", "utf8"); const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); const migration = await readFile("supabase/migrations/20260812220500_add_match_chat_actions.sql", "utf8"); expect(api).toContain('"date_proposal"'); expect(api).toContain('"location_proposal"'); expect(api).toContain("match_chat_proposal_responses"); expect(api).toContain("export async function PATCH"); expect(page).toContain("Proponer fecha"); expect(page).toContain("Proponer ubicación"); expect(page).toContain("Me viene bien"); expect(page).toContain("No puedo"); expect(migration).toContain("match_chat_proposal_responses") })
  it("autocomplete mentions and makes mention notifications mandatory", async () => { const api = await readFile("src/app/api/matches/[matchId]/chat/route.ts", "utf8"); const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); const push = await readFile("src/lib/serverPushDispatch.ts", "utf8"); const center = await readFile("src/app/notifications/page.tsx", "utf8"); const es = await readFile("src/i18n/locales/es.ts", "utf8"); expect(api).toContain("mentionedUserIds"); expect(api).toContain("mentionedPlayerIds"); expect(page).toContain("mentionSuggestions"); expect(page).toContain("participants.filter((item) => item.userId)"); expect(page).toContain("insertMention"); expect(push).toContain("mentionedUserIds.has(recipient.userId)"); expect(push).toContain("hasMandatoryMention"); expect(push).toContain("te ha mencionado"); expect(center).toContain("mentionedPlayerIds"); expect(es).toContain("Las menciones @ siempre se notifican") })
  it("requires preferred side and dominant hand for new and existing incomplete profiles", async () => { const api = await readFile("src/app/api/account/profile/route.ts", "utf8"); const gate = await readFile("src/components/auth/ProfileCompletionGate.tsx", "utf8"); const settings = await readFile("src/components/settings/AccountProfileSettings.tsx", "utf8"); expect(api).toContain("normalizePreferredPlayerSide(user.preferredSide)"); expect(api).toContain("normalizeDominantHand(user.dominantHand)"); expect(api).toContain("if (hasPreferredSide && !preferredSide)"); expect(api).toContain("if (hasDominantHand && !dominantHand)"); expect(gate).toContain("initialPreferredSide"); expect(gate).toContain("initialDominantHand"); expect(gate).toContain("dominantHandRequired"); expect(gate).toContain("required"); expect(settings).toContain('value="right"'); expect(settings).toContain('value="left"') })
  it("keeps preferred side out of list chips and integrates it into match detail and profile metadata", async () => { const detail = await readFile("src/components/match/MatchDetailPairingPanel.tsx", "utf8"); const teams = await readFile("src/components/player/TeamPlayers.tsx", "utf8"); const matchTeams = await readFile("src/components/matches/MatchTeamsPanel.tsx", "utf8"); const profile = await readFile("src/components/player/PlayerProfileScreen.tsx", "utf8"); expect(detail).toContain('const positionLine = <p className={metadataClass}>{position ? tx(`#${position} en liga`) : "\\u00a0"}</p>'); expect(detail).toContain("const playLine = playerPositionLabel ? ("); expect(detail).toContain("{showRankingPosition ? positionLine : null}"); expect(detail).not.toContain('text-neutral-400">{getPreferredPlayerSideLabel'); expect(teams).not.toContain("showPreferredSide"); expect(matchTeams).not.toContain("showPreferredSide"); expect(profile).toContain("getPlayerSideAndHandLabel"); expect(profile).toContain('{tx("Posición preferida ·")}{" "}{playerPositionLabel}') })

  it("makes availability recommendations optional per season and disabled by default", async () => {
    const provider = await readFile("src/context/SeasonSettingsProvider.tsx", "utf8")
    const schedule = await readFile("src/components/match/MatchScheduleForm.tsx", "utf8")
    const settings = await readFile("src/app/settings/page.tsx", "utf8")
    const profileGate = await readFile("src/components/auth/ProfileCompletionGate.tsx", "utf8")
    const migration = await readFile("supabase/migrations/20260813080000_add_optional_season_availability.sql", "utf8")
    expect(provider).toContain("availabilityRecommendationsEnabled: boolean")
    expect(provider).toContain("availabilityRecommendationsEnabled: false")
    expect(schedule).toContain("!isFinished && availabilityRecommendationsEnabled")
    expect(settings).toContain("roundSettings.availabilityRecommendationsEnabled")
    expect(profileGate).not.toContain("<StandardAvailabilityEditor")
    expect(migration).toContain("availability_recommendations_enabled boolean NOT NULL DEFAULT false")
    expect(migration).not.toContain("standard_availability_required")
  })

  it("shows preferred side as profile metadata without restoring chips elsewhere", async () => {
    const profile = await readFile("src/components/player/PlayerProfileScreen.tsx", "utf8")
    const matchDetail = await readFile("src/components/match/MatchDetailPairingPanel.tsx", "utf8")
    expect(profile).toContain('{tx("Posición preferida ·")}{" "}{playerPositionLabel}')
    expect(matchDetail).toContain('metadataPlacement={index === 0 ? "before-name" : "after-name"}')
  })

  it("stores dominant hand globally and exposes it as DIESTRO/ZURDO with the preferred side", async () => {
    const migration = await readFile("supabase/migrations/20260813094500_add_account_dominant_hand.sql", "utf8")
    const access = await readFile("src/app/api/access/route.ts", "utf8")
    const profile = await readFile("src/components/player/PlayerProfileScreen.tsx", "utf8")
    const personalProfile = await readFile("src/app/personal-matches/profile/page.tsx", "utf8")
    const detail = await readFile("src/components/match/MatchDetailPairingPanel.tsx", "utf8")
    expect(migration).toContain("dominant_hand")
    expect(migration).toContain("'right', 'left'")
    expect(access).toContain("dominant_hand")
    expect(access).toContain("dominantHand:")
    expect(profile).toContain("getPlayerSideAndHandLabel")
    expect(personalProfile).toContain("getPlayerSideAndHandLabel")
    expect(detail).toContain("getPlayerSideAndHandLabel")
  })

  it("orders mandatory profile fields and removes completion-screen clarifications", async () => { const gate = await readFile("src/components/auth/ProfileCompletionGate.tsx", "utf8"); const first = gate.indexOf("t.accountProfile.firstName"); const last = gate.indexOf("t.accountProfile.lastName"); const hand = gate.indexOf("t.accountProfile.dominantHand}"); const side = gate.indexOf("t.accountProfile.preferredSide}"); expect(first).toBeLessThan(last); expect(last).toBeLessThan(hand); expect(hand).toBeLessThan(side); expect(gate).not.toContain("t.accountProfile.description}"); expect(gate).not.toContain("t.accountProfile.globalNameNotice}"); expect(gate).not.toContain("t.accountProfile.preferredSideDescription}"); expect(gate).not.toContain("t.accountProfile.dominantHandDescription}") })
  it("keeps active and upcoming chats ahead of finished chats", async () => { const page = await readFile("src/app/chats/page.tsx", "utf8"); expect(page).toContain("const openChats = chats.filter((chat) => !chat.readOnly)"); expect(page).toContain("finishedChats = chats.filter((chat) => chat.readOnly)"); expect(page).toContain("const activeChats = openChats.filter"); expect(page).toContain("upcomingChats = openChats.filter"); expect(page).toContain('{tx("Activos")}</h2>'); expect(page).toContain('{tx("Próximos")}</h2>'); expect(page).toContain("Chats finalizados"); expect(page.indexOf('{tx("Activos")}</h2>')).toBeLessThan(page.indexOf('{tx("Chats finalizados")}</h2>')); expect(page.indexOf('{tx("Próximos")}</h2>')).toBeLessThan(page.indexOf('{tx("Chats finalizados")}</h2>')); expect(page).toContain("Solo lectura") })

})
