import { readFile } from "node:fs/promises"
import { describe, expect, it } from "vitest"

describe("v1.8.11 chat proposal polish and compact conversations", () => {
  it("lets every selected proposal time be removed compactly and removes the old fallback explanation", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); expect(page).toContain("dateOptions.map((item)"); expect(page).toContain("function removeDateOption"); expect(page).toContain('aria-label={`Quitar ${label}`}'); expect(page).toContain("calendarWeekday(localDateValue(date))"); expect(page).not.toContain("si nadie ha informado disponibilidad, se parte de la próxima hora en punto") })
  it("keeps the larger rotated send glyph and a full-bleed message scroller", async () => { const [page, shared, sendIcon] = await Promise.all([readFile("src/app/match/[id]/chat/page.tsx", "utf8"), readFile("src/components/match/chat/MatchChatShared.tsx", "utf8"), readFile("src/components/match/MatchChatSendIcon.tsx", "utf8")]); expect(page).toContain("<MatchChatComposer"); expect(shared).toContain("<MatchChatSendIcon />"); expect(sendIcon).toContain('className="h-[23px] w-[23px]"'); expect(sendIcon).toContain('rotate(25deg)'); expect(page).toContain('data-tour="chat-messages" className="flex min-h-0 flex-1 flex-col overflow-hidden bg-neutral-100"'); expect(page).toContain('ref={messagesRef} className="min-h-0 flex-1 overflow-y-auto'); expect(page).not.toContain('data-tour="chat-messages" className="mx-3') })
  it("shows live match statuses and keeps chat cards visually joined", async () => { const page = await readFile("src/app/chats/page.tsx", "utf8"); const api = await readFile("src/app/api/chats/route.ts", "utf8"); expect(page).toContain('coordinationStatus: "coordinating" | "awaiting_booking" | null'); expect(page).toContain('["Coordinando", "violet"]'); expect(page).toContain('["Pendiente de reserva", "indigo"]'); expect(page).toContain('index ? "-mt-px" : ""'); expect(page).toContain('"!rounded-t-xl !rounded-b-none"'); expect(page).toContain('"!rounded-b-xl !rounded-t-none"'); expect(api).toContain("buildMatchChatCoordination"); expect(api).toContain("coordinationStatus") })
  it("sorts messaging activity first and empty conversations by ascending round", async () => { const api = await readFile("src/app/api/chats/route.ts", "utf8"); expect(api).toContain("if (at || bt)"); expect(api).toContain("at ? -1 : 1"); expect(api).toContain("return a.round - b.round") })
  it("adds contextual guides for the chats list and the match chat", async () => { const tours = await readFile("src/features/onboarding/tours.ts", "utf8"); const types = await readFile("src/features/onboarding/types.ts", "utf8"); expect(types).toContain('| "chats"'); expect(types).toContain('| "chat"'); expect(tours).toContain('route: "/chats"'); expect(tours).toContain('route: "/match/:id/chat"'); expect(tours).toContain("[data-tour='chats-conversations']"); expect(tours).toContain("[data-tour='chat-messages']") })
})
