import { readFile } from "node:fs/promises"
import { describe, expect, it } from "vitest"

describe("v1.8.16 chats priority, contextual push and default appearance", () => {
  it("suppresses chat push on a visible matching chat and sends chat milestone metadata", async () => { const sw = await readFile("public/sw.js", "utf8"), dispatch = await readFile("src/lib/serverPushDispatch.ts", "utf8"), route = await readFile("src/app/api/matches/[matchId]/chat/route.ts", "utf8"); expect(sw).toContain('client.visibilityState === "visible"'); expect(sw).toContain('`/match/${payload.chatMatchId}/chat`'); expect(dispatch).toContain("chatMatchId:"); expect(dispatch).toContain('kind === "proposal_four_votes"'); expect(dispatch).toContain('kind === "coordination_status"'); expect(route).toContain("beforeVotes < 4 && afterVotes >= 4"); expect(route).toContain("beforeCoordination.status !== afterCoordination.status") })
  it("keeps the match chat action participant-only", async () => { const page = await readFile("src/app/match/[id]/page.tsx", "utf8"); expect(page).toContain('chatHref={isMatchParticipant ? `/match/${match.id}/chat` : null}') })
  it("defaults new devices to light colorful indigo without overriding stored choices", async () => { const theme = await readFile("src/context/ThemeProvider.tsx", "utf8"), layout = await readFile("src/app/layout.tsx", "utf8"); expect(theme).toContain('DEFAULT_THEME_MODE: ThemeMode = "light"'); expect(theme).toContain('DEFAULT_VISUAL_STYLE: VisualStyle = "colorful"'); expect(theme).toContain('DEFAULT_COLORFUL_PALETTE: ColorfulPalette = "indigo"'); expect(layout).toContain("s=l==='colorful'?'colorful':tm.indexOf(l)>=0?'plain':'colorful'") })
  it("splits active and upcoming chats and promotes any future chat with messages", async () => { const page = await readFile("src/app/chats/page.tsx", "utf8"); expect(page).toContain('Boolean(chat.lastMessage) || nextRound === null || chat.round <= nextRound'); expect(page).toContain('data-tour="chats-upcoming"'); expect(page).toContain('>Activos</h2>'); expect(page).toContain('>Próximos</h2>') })
  it("keeps CHAT tour controls visible without relying on the navbar", async () => { const overlay = await readFile("src/components/onboarding/GuidedTourOverlay.tsx", "utf8"), tours = await readFile("src/features/onboarding/tours.ts", "utf8"); expect(overlay).toContain("isMatchChatRoute"); expect(overlay).toContain("flex flex-col overflow-hidden"); expect(overlay).toContain("flex shrink-0 items-center"); expect(tours).toContain('{ key: "chat", version: 6'); expect(tours).toContain("[data-tour='chats-upcoming']") })
})
