import { readFile } from "node:fs/promises"
import { describe, expect, it } from "vitest"

describe("v1.8.8 optimistic chat UX", () => {
  it("renders outgoing messages and proposals before the POST resolves", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); const optimistic = page.indexOf("setMessages((current) => [...current, optimisticMessage])"); const request = page.indexOf('method: "POST"', optimistic); expect(optimistic).toBeGreaterThan(-1); expect(request).toBeGreaterThan(optimistic); expect(page).toContain("optimisticPayload"); expect(page).toContain("createOptimisticClientId"); expect(page).toContain("globalThis.crypto.getRandomValues"); expect(page).not.toContain("Date.now"); expect(page).not.toContain("Math.random"); expect(page).toContain("mergePendingMessages"); expect(page).toContain('void post("date_proposal", { options })'); expect(page).toContain('void post("location_proposal", { name, locationId: known?.id ?? null })') })
  it("updates votes before PATCH and never disables vote controls for network latency", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); const optimistic = page.indexOf("optimisticResponse: ProposalResponse"); const update = page.indexOf("setMessages((current) => current.map", optimistic); const request = page.indexOf('method: "PATCH"', update); expect(optimistic).toBeGreaterThan(-1); expect(update).toBeGreaterThan(optimistic); expect(request).toBeGreaterThan(update); expect(page).not.toContain("responding"); expect(page).not.toContain("disabled={Boolean(responding)}") })
  it("keeps server reconciliation in the background instead of awaiting a visible refresh", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); expect(page).toContain("if (response.ok) void loadFromServer()"); expect(page).toContain("void loadFromServer() }"); expect(page).not.toContain("await loadFromServer()") })
  it("rolls back only failed optimistic actions and keeps the composer reusable", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); expect(page).toContain("current.filter((message) => message.id !== optimisticId)"); expect(page).toContain("setBody((current) => current || previousBody)"); expect(page).toContain("...(original ? [original] : [])"); expect(page).toContain('disabled={!body.trim()}'); expect(page).not.toContain("sending") })
  it("reconciles pending messages through the API payload without duplicates", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); const api = await readFile("src/app/api/matches/[matchId]/chat/route.ts", "utf8"); expect(page).toContain("pendingMessagesRef.current.set"); expect(page).toContain("pendingMessagesRef.current.delete"); expect(page).toContain("messageClientId"); expect(api).toContain("clientId?: unknown"); expect(api).toContain("clientId ? { clientId } : {}"); expect(api).toContain("...(clientId ? { clientId } : {})") })
  it("derives the coordination panel from optimistic messages immediately", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); expect(page).toContain("buildMatchChatCoordination"); expect(page).toContain("displayedCoordination"); expect(page).toContain('matchStatus: match?.status ?? "scheduling"'); expect(page).not.toContain("const displayedCoordination = useMemo") })
})
