import { readFile } from "node:fs/promises"
import { describe, expect, it } from "vitest"

describe("v1.8.9 chat identity, read receipts and unread affordance", () => {
  it("returns profile images and per-participant read timestamps without adding a new public chat store", async () => { const api = await readFile("src/app/api/matches/[matchId]/chat/route.ts", "utf8"); expect(api).toContain('from("app_users").select("id,avatar_url")'); expect(api).toContain('from("match_chat_reads").select("user_id,last_read_at")'); expect(api).toContain("participantsWithReads"); expect(api).toContain("lastReadAt:"); expect(api).toContain("includeOverview: false") })
  it("groups consecutive senders and renders one avatar plus stable sender colors", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); expect(page).toContain("CHAT_PERSON_COLORS"); expect(page).toContain("participantColorClass"); expect(page).toContain("previousSameSender"); expect(page).toContain("<PlayerAvatar"); expect(page).toContain("!previousSameSender ? <PlayerAvatar") })
  it("shows WhatsApp-like send/read confirmation on own messages and proposals", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); expect(page).toContain("function MessageReceipt"); expect(page).toContain('"Leído por todos"'); expect(page).toContain('allRead ? "✓✓" : "✓"'); expect(page).toContain("Date.parse(item.lastReadAt) >= Date.parse(message.created_at)"); expect(page.match(/<MessageReceipt message=\{message\}/g)?.length).toBeGreaterThanOrEqual(2) })
  it("uses a compact circular unread badge per conversation", async () => { const page = await readFile("src/app/chats/page.tsx", "utf8"); expect(page).toContain("h-5 min-w-5"); expect(page).toContain("rounded-full bg-neutral-950"); expect(page).toContain("mensaje${chat.unread === 1 ? \"\" : \"s\"} sin leer") })
})
