import { readFile } from "node:fs/promises"
import { describe, expect, it } from "vitest"

describe("v1.8.9 chat identity, read receipts and unread affordance", () => {
  it("returns profile images and per-participant read timestamps without adding a new public chat store", async () => { const api = await readFile("src/app/api/matches/[matchId]/chat/route.ts", "utf8"); expect(api).toContain('from("app_users").select("id,avatar_url")'); expect(api).toContain('from("match_chat_reads").select("user_id,last_read_at")'); expect(api).toContain("participantsWithReads"); expect(api).toContain("lastReadAt:"); expect(api).toContain("includeOverview: false") })
  it("groups consecutive senders and renders one avatar plus stable sender colors through the shared chat bubble", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); const shared = await readFile("src/components/match/chat/MatchChatShared.tsx", "utf8"); expect(page).toContain("previousSameSender"); expect(page).toContain("<MatchChatTextMessage"); expect(shared).toContain("CHAT_PERSON_COLORS"); expect(shared).toContain("getMatchChatParticipantColorClass"); expect(shared).toContain("<PlayerAvatar"); expect(shared).toContain("!previousSameSender ? (") })
  it("shows WhatsApp-like send/read confirmation on own messages and proposals with the shared receipt", async () => { const page = await readFile("src/app/match/[id]/chat/page.tsx", "utf8"); const shared = await readFile("src/components/match/chat/MatchChatShared.tsx", "utf8"); expect(shared).toContain("function MatchChatMessageReceipt"); expect(shared).toContain('"Leído por todos"'); expect(shared).toContain('allRead ? "✓✓" : "✓"'); expect(shared).toContain("Date.parse(item.lastReadAt) >= Date.parse(message.created_at)"); expect(shared).toContain("<MatchChatMessageReceipt"); expect(page).toContain("<MatchChatMessageReceipt") })
  it("uses a compact circular unread badge per conversation", async () => { const page = await readFile("src/app/chats/page.tsx", "utf8"); expect(page).toContain("h-5 min-w-5"); expect(page).toContain("rounded-full bg-neutral-950"); expect(page).toContain("mensaje${chat.unread === 1 ? \"\" : \"s\"} sin leer") })
})
